### PR TITLE
update enrollment screen with new mockup

### PR DESCRIPTION
**Pull request by nathanstitt**
screen shot 2016-06-14 at 1 03 38 pm

### CODE REVIEW

**Comment by kathi-fletcher** [comment]
This is beautiful, but this particular ticket: https://www.pivotaltracker.com/story/show/121511693 is for tutor rather than concept coach (and of course we want for concept coach, too, but CC is in this ticket: https://www.pivotaltracker.com/story/show/118301997

Does this PR fix it both places?

**Comment by pandafulmanda** [comment]
I believe this is only for concept coach

**Comment by jason-holmes** [comment]
@pandafulmanda @nathanstitt We need to get an <hr> separator after the instructor and a label for the field.  Please see http://3h6cso.axshare.com/#p=cc_student_enrollment_code.

**Comment by jason-holmes** [comment]
We need to get an horizontal rule and a label for the input field.  Also agree with @nathanstitt on black text too jarring.  Please use grey heading color for text.  See http://3h6cso.axshare.com/#p=cc_school_id for CC mockup.

**Pull request merged**
