### PR TITLE
continue amendment

### PR DESCRIPTION
**Pull request by pandafulmanda**
screen shot 2016-01-27 at 6 14 48 pm

Fixes concerns from #109, related to Connexions/webview#1358
- remove Continue from breadcrumbs
- replaces bottom button with continue to next reading link
- add message and continue to next reading link at the top
- separate reading title from link to book

See also [this ticket](https://www.pivotaltracker.com/n/projects/1156756/stories/112456797).  Thoughts? @jason-holmes @Fredasaurus @kathi-fletcher, kajal what should happen when I am viewing a previously completed exercise from progress?  i.e. i've opened the coach on 1.4 and while I don't complete this one, I click on progress, and view my completed 1.3.  Should the continue say, 1.5? or 1.4?

### CODE REVIEW

**Comment by pandafulmanda** [comment]
@kajalp what do you think?

**Comment by kajalp** [comment]
I like it.. lets send it to Kathi and Jason. We are keeping the button down below right?

**Comment by jason-holmes** [comment]
Yes, we should keep it and the label should be "Return to reading"

**Comment by pandafulmanda** [comment]
@jason-holmes why "Return to reading" and not also "Continue to ______"

**Comment by jason-holmes** [comment]
I was suggesting using the same label as the text after the pipe at the top.  They do the same thing, which is "Return to reading", right?

**Comment by pandafulmanda** [comment]
i was thinking the button at the bottom would take people to the continue on the next page?

**Comment by pandafulmanda** [comment]
so more like this? @kathi-fletcher @jason-holmes @Fredasaurus 

screen shot 2016-01-27 at 2 16 07 pm

**Comment by pandafulmanda** [comment]
@kathi-fletcher @jason-holmes i've updated with the latest screenshot, and I'm now considering this as ready for review @philschatz

**Pull request merged**
