### PR TITLE
Ask for enrollment code before sign-in

### PR DESCRIPTION
**Pull request by nathanstitt**
No user visible changes other than there's now a different sign up flow depending on if the user is signed in or not.

If they are logged in:
- User starts CC 
- Prompted for enrollment code
- an enrollment request is created.  This can fail because the code is invalid or the user was dropped.
- User then confirms the enrollment by entering the student id

If they are not logged in:
- User starts CC 
- Prompted for enrollment code
- Code is validated against the course. 
- **user logs in or signs up**
- an enrollment request is created.  Note that the enrollment can still fail if the account that the user signs in as was dropped.
- User then confirms the enrollment by entering the student id

Pairs with https://github.com/openstax/tutor-server/pull/911

### CODE REVIEW

**Comment by philschatz** [comment]
Looks good! Once this is merged can you make a PR to webview with the new hash?

**Comment by jpslav** [comment]
BE PR merged @philschatz

**Comment by nathanstitt** [comment]
yes, will do so.

**Comment by philschatz** [comment]
Kajal pointed out that this method is problematic because if a student logs out of CC and then reloads the page they will be asked for the enrollment code (which they already entered) before the login.

I don't think cookies will fix it; if the student is on a public computer it's still an issue.

/cc @kathi-fletcher @pandafulmanda

**Comment by philschatz** [comment]
ok. Conclusion (from chatting w/ kajal & @Fredasaurus) was to change the "Enrollment Code" screen to show 2 columns when not logged in (and 1 column if logged in):

```
Already entered the Enrollment Code?        |    First time here?
                                            |
[LOG IN]                                    |    Enter Enrollment Code:
                                            |    [______]
                                            |    [Go]
```

If the student is already logged in then we would just show the 2nd column (without the "First time here?" header)

**Comment by nathanstitt** [comment]
Above screen is implemented by PR #115

**Pull request merged**
