### PR TITLE
take out full loash and use underscore in CC as possible

### PR DESCRIPTION
**Pull request by pandafulmanda**
not for release in December, requires more testing

### CODE REVIEW

**Comment by philschatz** [comment]
Why use underscore instead of lodash (or just the parts of lodash CC uses?)

**Comment by pandafulmanda** [comment]
this let's us exclude `lodash` from our build and use the `underscore` from webview for example.  including each specific part of `lodash` that we are using in here would add bloat

**Comment by philschatz** [comment]
Hmm, I'm surprised @dak used underscore instead of lodash in webview. but it looks like webview doesn't build concept-coach ([webview/src/scripts/config.js](https://github.com/Connexions/webview/blob/dad4f5dcafac7f117587b9de49d0ed375a7f5c78/src/scripts/config.js#L29) so how would they use the same underscore? It seems like using only the lodash parts we need _would_ currently reduce the JS size, no?

**Comment by dak** [comment]
We were using lodash, but switched back to underscore both due to some compatibility issues and also because at the time lodash publicly stated its intent to merge back with underscore.

**Comment by pandafulmanda** [comment]
both jQuery and lodash are [being loaded externally](https://github.com/openstax/concept-coach/blob/master/webpack-helper/configs.coffee#L48-L51).  Also, I don't think this should be merged in until later, post this week's deploy.  I think it's worth having more hands testing this change.

**Comment by philschatz** [comment]
ah, thanks @pandafulmanda ! Sticking it in the holding pen. I think the only thing going out this week are the math fixes.

**Pull request merged**
