### PR TITLE
Add laptop with mug and style signup or login screen

### PR DESCRIPTION
**Pull request by nathanstitt**
screen shot 2016-06-27 at 3 58 00 pm

### CODE REVIEW

**Comment by kjdav** [comment]
@nathanstitt the mockup had another "sign in" in the upper right hand corner (next to Close); did that make it in?

**Comment by nathanstitt** [comment]
no, that was missed.  Sorry.   

@openstax/ux - what's the relative importance of the sign-in link beside the close button ?  We missed that on this PR

**Comment by jason-holmes** [comment]
We can live without it.  We still have the sign in in the body.  The upper right sign in was added since it's a common pattern on the web and some users might expect it there.

**Comment by kjdav** [comment]
@jason-holmes Do you think we should adjust the last line to compensate for losing the other Sign in, or ok as-is? 

Ideas: 1) shift the "Already have an account? Sign in" line lower, to set it apart from the Sign Up information. 2) format the last line differently to set it apart visually?

**Comment by jason-holmes** [comment]
Nah.  I think it's OK.  It's blue and linky looking and in context of the user's activity.  It's good.

**Pull request merged**
