### PR TITLE
Register for concept coach course

### PR DESCRIPTION
**Pull request by nathanstitt**
TODO:
- [x] figure out how to detect if user is already a member of course.
- [x] Submit request only if not already a member
- [x] make somewhat pretty
### Registration code entry:

screen shot 2015-11-11 at 5 32 08 pm
### Validation

screen shot 2015-11-11 at 5 32 17 pm
### Success message is displayed for 1.5 secs then tasks are started

screen shot 2015-11-11 at 5 32 50 pm

### CODE REVIEW

**Comment by nathanstitt** [comment]
A question on registering for courses.  Currently this is failing because we're passing in just the UUID and the controller is expecting both the UUID and version.  This check https://github.com/openstax/tutor-server/blob/master/app/controllers/api/v1/enrollment_changes_controller.rb#L52 is failing

Will CNX be able to pass in the version along with the content UUID?

**Comment by pandafulmanda** [comment]
yes it will

**Comment by jpslav** [comment]
@Dantemss, I don't think we want to be checking the version, since it will
happen that an ecosystem is at version X but the book has moved on to
version X+Y.  Can you check out the code and see if we can remove the
version check that NS mentions?

**Comment by nathanstitt** [comment]
@JP, yeah that's what I was wondering.  @Dantemss, I can make  a PR to remove the check.  I've got it fixed already locally here so I could test.   Thanks!

**Comment by jpslav** [comment]
We need to still check that the UUID matches, just not the version

**Comment by Dantemss** [comment]
I will remove the version.

**Comment by nathanstitt** [comment]
@Dantemss, I've made a PR to do so at: https://github.com/openstax/tutor-server/pull/804  Feel free to take that over and do whatever you think it needs :)  Thanks!

**Comment by Dantemss** [comment]
Oh great :)

**Pull request merged**
