### PR TITLE
Allow teachers to register for courses (fixes 422 error)

### PR DESCRIPTION
**Pull request by nathanstitt**
image

### CODE REVIEW

**Comment by philschatz** [comment]
While it may work (and maybe we can still merge) I think 422 Unprocessable Entity  is an incorrect response to send if we are still able to enroll.

**Comment by nathanstitt** [comment]
Well the BE was returning that because we failed to check if a user was a _student_ on a course.  As long as they where a member of the course we'd ask for CC tasks.  I think the BE returns 422 for all errors and then also sets the body with some json that describes the error.

**Comment by pandafulmanda** [comment]
:+1:

**Comment by kathi-fletcher** [comment]
OK -- Courtney reviewed wording and came up with the following:

"
Welcome! 

To see the student view of your course in Concept Coach, enter an enrollment code from one of your sections.

We suggest creating a test section for yourself so you can separate your Concept Coach responses from those of your students.
"
The smaller font for the suggestion part is good.

**Comment by pandafulmanda** [comment]
also closes #59

**Pull request merged**
